services:
  app:
    build:
        context: ./be_graphql
        dockerfile: .Dockerfile
    ports:
        - 37211:4000
    container_name: app_backend_graphql
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://admin:secret@mongodb:27017
      - DB_NAME=pokemonDb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
  
  fe_test:
    build:
      context: ./fe_test
      dockerfile: .Dockerfile
    ports:
      - 37212:80
    container_name: frontend_react
